packages/plugin/src/protobufts-plugin.ts
Hey @timostamm here is a draft PR. 
I have a couple questions for you.
What do you think about the style `--long_type=number|string|bigint` ?
I actually prefer it over `long_type_number`, ...
But it would probably makes sense to do the same for `---client=...`, `--optimize` and `--force_optimize`.
So I guess up to you to take the decision as the maintainer of this lib.
(If you decide for `key=value` then it would make sense to add a `values: string[]` in the parameter spec to automate the declaration).
My second question is about testing:
When I run `make` in the root folder I end up with some error:
```
[...]
@protobuf-ts/runtime-rpc: 'clean' done
@protobuf-ts/plugin-framework: 'clean' done
@protobuf-ts/runtime-rpc: es6 done
@protobuf-ts/plugin-framework: es6 done …
```
=> Add long_type_number and long_type_bigint parameters.

packages/plugin/src/message-type-extensions/well-known-types.ts, packages/test-generated/spec/google.protobuf.timestamp.spec.ts, packages/test-generated/spec/support/helpers.ts
Fixes issue #22 Adds coverage.
=> fix RangeError in google.protobuf.Timestamp.fromDate()

packages/grpcweb-transport/Makefile, packages/grpcweb-transport/tsconfig.json, packages/plugin-framework/Makefile, packages/plugin-framework/tsconfig.json, packages/plugin/tsconfig.json, packages/runtime-rpc/Makefile, packages/runtime-rpc/tsconfig.json, packages/runtime/Makefile, packages/runtime/tsconfig.json, packages/twirp-transport/Makefile, packages/twirp-transport/tsconfig.json
Should fix #38.  
Needs testing.  
Should be backported to v1.x
=> Do not output source mappings and declaration mappings

packages/plugin-framework/src/typescript-import-manager.ts
(cherry picked from commit 4deed7c9cd7a5bb435e1b050ccfeae3bdcb5d5ed)
=> Fix windows import path in v1.x

CHANGELOG.md, packages/protoc/README.md, packages/protoc/protoc.js, packages/protoc/util.js
=> prefer protoc from $PATH 

CHANGELOG.md, packages/plugin-framework/spec/descriptor-info.spec.ts, packages/plugin-framework/src/descriptor-info.ts, packages/plugin-framework/src/type-names.ts
See #59.
Added test coverage. Created fix. Added to CHANGELOG.md.
=> Fix the broken generate_dependencies parameter.

packages/grpcweb-transport/src/grpc-web-options.ts, packages/grpcweb-transport/src/grpc-web-transport.ts, packages/twirp-transport/src/twirp-options.ts, packages/twirp-transport/src/twirp-transport.ts
implements the suggested solution in #95
fixes #95
=> add fetchInit to RpcOptions for grpc-web and twirp (#95)

packages/plugin/src/out-file.ts
The issues related to this change
https://github.com/timostamm/protobuf-ts/issues/256#issuecomment-1105204434
=> Fix line breaks in header comments

packages/runtime/src/binary-format-contract.ts, packages/runtime/src/binary-reader.ts, packages/runtime/src/binary-writer.ts, packages/runtime/src/index.ts, packages/runtime/src/message-type.ts
=> Avoid cyclic import in binary format contract

packages/runtime/spec/reflection-merge-partial.spec.ts, packages/runtime/src/reflection-merge-partial.ts
See https://github.com/timostamm/protobuf-ts/issues/266
=> Treat null values the same as undefined when generating protobuf messages

packages/runtime-rpc/src/client-streaming-call.ts, packages/runtime-rpc/src/duplex-streaming-call.ts, packages/runtime-rpc/src/server-streaming-call.ts, packages/runtime-rpc/src/unary-call.ts
=> Use Promise as return type for call.then()

packages/protoc/util.js
Add support for protoc to be detected in path also on Windows.
=> fix: find protoc in path also in windows

packages/runtime/src/binary-reader.ts
=> Ignore byte-order mark

packages/example-angular-app/src/app/grpcweb-server-streaming/grpcweb-server-streaming.component.html, packages/example-angular-app/src/app/grpcweb-server-streaming/grpcweb-server-streaming.component.ts, packages/example-angular-app/src/app/grpcweb-unary/grpcweb-unary.component.html, packages/example-angular-app/src/app/grpcweb-unary/grpcweb-unary.component.ts, packages/example-chat-system/browser-client/index.ts, packages/example-chat-system/terminal-client/client.ts
=> Cleanup deadline from RPCOptions/GrpcWebOptions

packages/protoc/util.js
* Following @timostamm 's feedback in #510 to support osx updated
* Address issue #515 for win32
* Support linux arm64 version
=> feat: update arch for fetching binary

packages/runtime/src/message-type-contract.ts, packages/runtime/src/message-type.ts
Fixes https://github.com/timostamm/protobuf-ts/issues/614
=> Fix `messagePrototype` for `exactOptionalProperties: true`

packages/test-conformance/src/gen/optimize_code_size-long_type_bigint/google/protobuf/test_messages_proto2.ts, packages/test-conformance/src/gen/optimize_code_size-long_type_bigint/google/protobuf/test_messages_proto3.ts, packages/test-conformance/src/gen/optimize_code_size-long_type_string/google/protobuf/test_messages_proto2.ts, packages/test-conformance/src/gen/optimize_code_size-long_type_string/google/protobuf/test_messages_proto3.ts, packages/test-conformance/src/gen/optimize_speed-long_type_bigint/google/protobuf/test_messages_proto2.ts, packages/test-conformance/src/gen/optimize_speed-long_type_bigint/google/protobuf/test_messages_proto3.ts, packages/test-conformance/src/gen/optimize_speed-long_type_string/google/protobuf/test_messages_proto2.ts, packages/test-conformance/src/gen/optimize_speed-long_type_string/google/protobuf/test_messages_proto3.ts
Following https://github.com/timostamm/protobuf-ts/pull/670
=> Regenerate code

Makefile
=> Publish with npm

packages/plugin/src/message-type-extensions/well-known-types.ts, packages/test-default/gen/google/protobuf/timestamp.ts, packages/test-default/spec/google.protobuf.timestamp.spec.ts, packages/test-force_optimize_code_size/gen/google/protobuf/timestamp.ts, packages/test-force_optimize_code_size/spec/google.protobuf.timestamp.spec.ts, packages/test-force_optimize_speed,long_type_string/gen/google/protobuf/timestamp.ts, packages/test-force_optimize_speed,long_type_string/spec/google.protobuf.timestamp.spec.ts, packages/test-force_optimize_speed/gen/google/protobuf/timestamp.ts, packages/test-force_optimize_speed/spec/google.protobuf.timestamp.spec.ts, packages/test-long_type_string/gen/google/protobuf/timestamp.ts, packages/test-long_type_string/spec/google.protobuf.timestamp.spec.ts
=> Ensure non-negative nanos in Timestamp.fromDate()

packages/grpcweb-transport/spec/grpc-web-transport.spec.ts, packages/grpcweb-transport/src/grpc-web-options.ts, packages/grpcweb-transport/src/grpc-web-transport.ts
Fixes https://github.com/timostamm/protobuf-ts/issues/504
=> Allow GrpcWebFetchTransport to use a custom fetch function

package-lock.json, packages/twirp-transport/clientcompat/client.ts, packages/twirp-transport/clientcompat/run.bash, packages/twirp-transport/package.json
tsx instead of ts-node for faster CI.
=> Speed up Twirp tests

packages/plugin/src/code-gen/message-interface-generator.ts, packages/plugin/src/framework/typescript-imports.ts, packages/plugin/src/interpreter.ts, packages/plugin/src/message-type-extensions/create.ts, packages/plugin/src/message-type-extensions/internal-binary-read.ts, packages/plugin/src/message-type-extensions/internal-binary-write.ts, packages/plugin/src/protobufts-plugin.ts
Makes dependencies more visible.
=> Limit class member visibilities
