timostamm/protobuf-ts

- MANUAL.md
- packages/grpcweb-transport/src/grpc-web-format.ts
- packages/plugin/src/code-gen/field-info-generator.ts
- packages/runtime-rpc/src/deferred.ts
- packages/runtime/src/binary-format-contract.ts
- packages/runtime/src/reflection-info.ts
- packages/test-generated/tsconfig.bigint.json
- packages/test-generated/tsconfig.json
Const enums conflict with typescript compiler option "isolatedModules". See #3.
This PR:
- changes all const enum declarations to plain enum
- updates generated reflection information to numerical literal with a comment to keep code size small
- activates compiler option "isolatedModules" for the "test-generated" package to cover regressions
> Drop const enums - fixes #3

- MANUAL.md
Looks like the option here should be `optimize_code_size`
> docs: correct optimize_code_size option

- packages/plugin/src/message-type-extensions/internal-binary-read.ts
In my testing, I ran into unexpected behavior when interacting with javascript errors when I have a protobuf message called `Error`.
```proto
message Error {
// Field with the error
string field_name = 1;
// Error message
string message = 2;
}
```
After generating the interface and compiling my project, I get the following error:
```
Type error: This expression is not constructable.
Type `Error$Type` has no construct signatures.
```
Seems to be coming from https://github.com/timostamm/protobuf-ts/blob/72866167d93aa0471da25dc82475014465a08847/packages/runtime/src/reflection-binary-reader.ts#L48-L52
--
I have not tested this yet, working on getting my local environment set up. Let me know if there is anything else needed and whether this is valid @timostamm. 🍻
> Access Error through globalThis for generated code

- packages/grpcweb-transport/src/grpc-web-transport.ts
- packages/runtime-angular/src/lib/twirp-transport.service.ts
- packages/runtime-rpc/spec/rpc-interceptor.spec.ts
- packages/runtime-rpc/spec/server-streaming-call.spec.ts
- packages/runtime-rpc/spec/unary-call.spec.ts
- packages/runtime-rpc/src/client-streaming-call.ts
- packages/runtime-rpc/src/duplex-streaming-call.ts
- packages/runtime-rpc/src/rpc-call-shared.ts
- packages/runtime-rpc/src/rpc-options.ts
- packages/runtime-rpc/src/rpc-transport.ts
- packages/runtime-rpc/src/server-streaming-call.ts
- packages/runtime-rpc/src/unary-call.ts
- packages/test-generated/spec/service-all-methods.spec.ts
- packages/twirp-transport/src/twirp-transport.ts
The cancel method is a bit of a headache for adapting calls to Observables.
It also complicates RpcTransport implementation.
This breaking change removes the cancel method.
To cancel a call, RpcOptions now takes an AbortSignal.
> BC: Drop cancel() method of RPC calls.

- MANUAL.md
- packages/runtime/src/pb-long.ts
Safari 14 does have BigInt, but is missing the DataView bigint methods.
- Changed detection to check for all required methods.
- Added meaningful error message.
- Updated MANUAL.md
> Fix Safari 14 bigint detection

- packages/plugin/src/message-type-extensions/internal-binary-read.ts
There was a bug in internal-binary-read.ts
When the field option jstype = JS_STRING was set, the generated method `internalBinaryRead` would still read the field as a bigint.
This problem only surfaces if the plugin parameter long_type_string is *not* set and code is optimized for speed (instead of for code size).
> Fix jstype = JS_STRING field option for speed optimized code

- MANUAL.md
- packages/plugin-framework/src/string-format.ts
- packages/plugin/spec/interpreter.spec.ts
- packages/plugin/spec/protobufts-plugin-long.spec.ts
- packages/plugin/spec/protobufts-plugin.spec.ts
- packages/plugin/src/interpreter.ts
Hey Timo,
Proto fileds with `[jstype = JS_NUMBER]` were documented as `* @generated from protobuf field: [...] [jstype = JS_STRING];`
This is fixed in `string-format.ts`.
While I was looking for the correct place to fix this I found some fishy code in `interpreter.ts` where the normal type (i.e. BigInt) is not taken into account. I am not sure if the change is correct as I don't know where/how to test this. I'm happy to work on the tests if you can give me some pointers.
Thanks,
Vic
> fix long fields.

- packages/plugin-framework/src/typescript-import-manager.ts
Fixes generated import path on windows platform from:
```typescript
import { Any } from "./google\\protobuf\\any";
```
to:
```typescript
import { Any } from "./google/protobuf/any";
```
> Fix windows import path

- CHANGELOG.md
- packages/grpcweb-transport/src/grpc-web-transport.ts
- packages/runtime-angular/src/lib/twirp-transport.service.ts
- packages/runtime-rpc/spec/rpc-options.spec.ts
- packages/runtime-rpc/src/index.ts
- packages/runtime-rpc/src/rpc-options.ts
- packages/runtime-rpc/src/rpc-transport.ts
- packages/runtime-rpc/src/test-transport.ts
- packages/test-generated/spec/service-all-methods.spec.ts
- packages/twirp-transport/src/twirp-transport.ts
This is a simple function rename. The goal is just to keep it as simple as possible and the "extended" is not necessary for that.
Technically a breaking change because the function is part of the public API. But if there are minor breaking changes, this is one. The change only affects RpcTransport implementations.
> Refactor mergeExtendedRpcOptions => mergeRpcOptions

- CHANGELOG.md
- packages/plugin/src/code-gen/method-info-generator.ts
Generated service info is incorrect:
```typescript
{ name: "Unary", serverStreaming: false, clientStreaming: false, options: {}, I: ExampleRequest, O: ExampleResponse },
{ name: "ServerStream", clientStreaming: false, options: {}, I: ExampleRequest, O: ExampleResponse },
{ name: "ClientStream", serverStreaming: false, options: {}, I: ExampleRequest, O: ExampleResponse },
{ name: "Bidi", options: {}, I: ExampleRequest, O: ExampleResponse }
```
The generated properties are unnecessary. All true values are missing, for example serverStreaming: true for "ServerStream".
> Fix clientStreaming and serverStreaming properties

- packages/grpcweb-transport/src/grpc-web-format.ts
- packages/grpcweb-transport/src/grpc-web-transport.ts
Envoy replies with application/grpc-web+proto, regardless of the specified request content type.
Envoy only replies with application/grpc-web-text when the accept request header was set explicitly.
This fix sets `accept: application/grpc-web-text` when requesting in text format.
The fix also looks at the response content type to determine which format to parse.
> Support grpc-web-text format with envoy.

- packages/protoc/util.js
Download protoc-osx-x86_64 binary for both Intel & Apple CPUs on macos.
Also fix a typo on win32.
> Fix protoc arch detection on Apple Silicon

- packages/grpc-transport/src/grpc-options.ts
- packages/grpc-transport/src/grpc-transport.ts
- extract `CallOptions` from `GrpcOptions`
- create `@grpc/grpc-js` Client once in `GrpcTransport` constructor
- add `close` method, which closes `@grpc/grpc-js` Client
fixes #107
> fix: @protobuf-ts/grpc-transport memory leak

- packages/benchmarks/perf.ts
- packages/benchmarks/testees/protobufjs/Makefile
Partially address #123
Results of the perf benchmark on my machine:
```
google-protobuf             :     413.662 ops/s
ts-proto                    :   1,324.736 ops/s
protobuf-ts (speed)         :   1,461.452 ops/s
protobuf-ts (speed, bigint) :   1,475.889 ops/s
protobuf-ts (size)          :   1,250.677 ops/s
protobuf-ts (size, bigint)  :   1,255.167 ops/s
protobufjs                  :   1,732.049 ops/s
google-protobuf             :     906.883 ops/s
ts-proto                    :   3,805.993 ops/s
protobuf-ts (speed)         :     430.632 ops/s
protobuf-ts (speed, bigint) :     448.063 ops/s
protobuf-ts (size)          :     378.682 ops/s
protobuf-ts (size, bigint)  :     392.511 ops/s
protobufjs                  :   1,539.768 ops/s
ts-proto                    :   4,503.332 ops/s …
```
> Add perf benchmarks for protobufjs

- packages/plugin-framework/src/plugin-base.ts
> set stdout to block, fixes large file generation

- CHANGELOG.md
- MANUAL.md
- packages/example-angular-app/src/app/grpcweb-server-streaming/grpcweb-server-streaming.component.html
- packages/example-angular-app/src/app/grpcweb-server-streaming/grpcweb-server-streaming.component.ts
- packages/example-angular-app/src/app/grpcweb-unary/grpcweb-unary.component.html
- packages/example-node-grpcweb-transport-client/client.ts
- packages/grpc-transport/src/grpc-transport.ts
- packages/grpcweb-transport/src/grpc-web-format.ts
- packages/grpcweb-transport/src/grpc-web-transport.ts
- packages/runtime-rpc/spec/rpc-options.spec.ts
- packages/runtime-rpc/src/rpc-options.ts
Renames rpc option `deadline` to `timeout`. When a number is given, it is used as a timeout in milliseconds. When a Date is given, it is used as a deadline.
Fixes #99
> Support rpc timeout

- packages/runtime/src/binary-format-contract.ts
- packages/runtime/src/message-type-contract.ts
I had started using `MESSAGE_TYPE` introduced in 2.0.3 and have run into a problem due to `MESSAGE_TYPE` being a unique symbol. 
My setup is a Lerna monorepo with `packages/proto` carrying all proto definitions (the package devDepends on `@protobuf-ts/plugin`), and `packages/backendlib` containing a function that imports `MESSAGE_TYPE` to do redaction (this package depends on `@protobuf-ts/runtime`). I have a test that imports a proto type from `packages/proto`.
The problem is that `@protobuf-ts/runtime` package happens to be installed twice: both under `packages/proto/node_modules`  and `packages/backendlib/node_modules`. As such, `MESSAGE_TYPE` symbols are unequal (since each of them is unique), and `containsMessageType` function called from `packages/backendlib` code always returns …
> Use Symbol.for() to define MESSAGE_TYPE

- packages/grpcweb-transport/src/grpc-web-format.ts
When message ends with `128, 0, 0, 0, 0` and trailerData is empty, splitting it by `\r\n` resulting array contains one empty string.
This causes error:
```
RpcError: Cannot read property 'trim' of undefined
```
Also, if trailer has colon in content it stripping because of limit. See https://github.com/timostamm/protobuf-ts/issues/166
This PR fixes this bugs, according to grpc-web protocol.
> Update parseTrailer function to support empty trailers & trailers with colon in content

- MANUAL.md
- packages/plugin/spec/interpreter.spec.ts
- packages/plugin/src/interpreter.ts
- packages/plugin/src/our-options.ts
- packages/plugin/src/protobufts-plugin.ts
This new option, if specified, will instruct the plugin to NOT drop a common shared enum name prefix. By default, the prefix
is removed.
Motivation: my company has a huge legacy TypeScript codebase that uses protobuf.js-generated proto definitions. We want to migrate it to protobuf-ts. Some enums are very pervasive, converted from and to strings with prefix assumed, so it's easier to just keep the damn prefix where it is. 
We also have a ton of Go code where prefix is not removed, so for the sake of consistency I want to introduce this new option which is, of course, off by default.
> Add keep_enum_prefix plugin option

- packages/grpc-transport/src/grpc-transport.ts
- packages/grpcweb-transport/spec/grpc-web-transport.spec.ts
- packages/grpcweb-transport/src/grpc-web-transport.ts
- packages/runtime-angular/src/lib/twirp-transport.service.ts
- packages/runtime-rpc/spec/rpc-error.spec.ts
- packages/runtime-rpc/src/rpc-error.ts
- packages/twirp-transport/src/twirp-transport.ts
> Add service/method name to RpcError

- packages/plugin/src/our-options.ts
In #200, the `server_generic` option was incorrectly parsed to `ServerStyle.NO_SERVER`.
Fixes #202
> Fix server_generic plugin option

- .circleci/config.yml
- CHANGELOG.md
- packages/twirp-transport/Makefile
`go get` is no longer supported by go 1.18.
Switch to `go install` and bump CI to go 1.17.
> Support go 1.18 in build

- packages/plugin-framework/src/source-code-info.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> Replace deprecated String.prototype.substr()

- packages/grpc-backend/src/index.ts
We have a use case where we need to call `createDefinition` directly and not via `adaptService`. Would be great if this was exported
> export createDefinition from @protobuf-ts/grpc-backend

- packages/twirp-transport/src/twirp-transport.ts
Fetch responses in Cloudflare Workers currently throw an error on access of the "type" property[^1][^2]. This PR guards access of the property with a try/catch so that twirp clients can be used inside of Cloudflare Workers.
[^1]: https://developers.cloudflare.com/workers/runtime-apis/response/#properties
[^2]: https://github.com/cloudflare/miniflare/blob/72f046e/packages/core/src/standards/http.ts#L646
> twirp-transport: Guard access of response.type to support Cloudflare Workers

- CHANGELOG.md
- packages/grpcweb-transport/src/grpc-web-format.ts
- packages/twirp-transport/src/twirp-transport.ts
This is #321, but applied to the grpcweb-transport as well.
All tests pass locally.
> grpcweb-transport: Guard access of response.type to support Cloudflare Workers

- MANUAL.md
The base url is incorrect in the example, it requires a prefix
> Update baseURL in example

- packages/grpcweb-transport/spec/grpc-web-format.spec.ts
- packages/grpcweb-transport/spec/grpc-web-transport.spec.ts
- packages/grpcweb-transport/src/grpc-web-format.ts
- packages/grpcweb-transport/src/grpc-web-transport.ts
> grpcweb-transport: fix handling responses with empty body and status in headers

- packages/runtime/spec/reflection-merge-partial.spec.ts
- packages/runtime/src/reflection-merge-partial.ts
This addresses https://github.com/timostamm/protobuf-ts/discussions/319
```ts
const source = { bars: [1],    foos: [{ foo: 1 }] };
const target = { bars: [2, 3], foos: [{ foo: 2 }, { foo: 3 }] };
reflectionMergePartial(SomeMessageType, target, source);
```
| Repeated Field                                                      | Scalar/Enum        | Message            |
|---------------------------------------------------------------------|--------------------|--------------------|
| result target array is referentially equal to original target array | :x:                | :white_check_mark: |
| result target array is deeply equal to source array                 | :white_check_mark: | :x:                |
| result target array is **NOT** referentially equal to source array  | …
> Make repeated field merging consistent

- MANUAL.md
- packages/runtime/src/message-type-contract.ts
- packages/runtime/src/reflection-merge-partial.ts
Following up on discussion https://github.com/timostamm/protobuf-ts/discussions/319 and PR https://github.com/timostamm/protobuf-ts/pull/335, let's clarify the behavior of `mergePartial()` in the documentation.
> Clarify mergePartial() behavior

- packages/runtime-angular/package.json
Set the version constraint on the runtime-angular package to include Angular 14.
> Relaxed angular version constraints in runtime-angular

- packages/runtime/spec/pb-long.spec.ts
- packages/runtime/src/goog-varint.ts
Borrowed from https://github.com/protocolbuffers/protobuf/pull/8170, this PR is an alternative approach for https://github.com/timostamm/protobuf-ts/pull/366. (I'm the colleague.) 
The error in this optimization is that it incorrectly assumes that `bitsLow` is never negative, but that can occur when the highest bit is set due to 2s complement representation.
```
$ make
...
@protobuf-ts/runtime: 'test-node' ...
@protobuf-ts/runtime: Jasmine started
@protobuf-ts/runtime: Executed 622 of 622 specs SUCCESS in 0.45 sec.
```
> Alternative fix for int64toString

- packages/example-buf/proto/buf.lock
Just a quick drive-by `buf mod update` - we [made some changes](https://docs.buf.build/faq#googleapis-failure) to our hosted googleapis/googleapis module; this should fix any issues you might see!
> Run `buf mod update`

- packages/runtime/src/reflection-merge-partial.ts
> Avoid overwriting a set oneof field in target with an unset oneof field in source

- packages/grpc-transport/src/grpc-transport.ts
It seems that the `message` field of grpc-js errors contains the status code concatenated with the message. An error with invalid argument for example contains the following in `message`: `3 INVALID_ARGUMENT: something`.
It seems that the `details` field in the service error does not include that prefix, so I think that field should be used when constructing the RpcError.
> Use details from service error as RpcError message

- packages/protoc/package-lock.json
- packages/protoc/package.json
- packages/protoc/util.js
> make protoc installation script respect proxy env

- .github/workflows/ci.yaml
- README.md
- Enable CI on push to main and on tag.
- Remove CircleCI badge.
> CI update follow-ups

- packages/plugin/src/message-type-extensions/well-known-types.ts
- packages/runtime/src/reflection-json-reader.ts
- packages/runtime/src/reflection-json-writer.ts
- packages/test-conformance/failing_tests_optimize_code_size-long_type_bigint.txt
- packages/test-conformance/failing_tests_optimize_code_size-long_type_string.txt
- packages/test-conformance/failing_tests_optimize_speed-long_type_bigint.txt
- packages/test-conformance/failing_tests_optimize_speed-long_type_string.txt
- packages/test-conformance/proto/conformance/conformance.proto
- packages/test-conformance/proto/google/protobuf/test_messages_proto2.proto
- packages/test-conformance/proto/google/protobuf/test_messages_proto3.proto
- packages/test-conformance/src/gen/optimize_code_size-long_type_bigint/conformance/conformance.ts
- packages/test-conformance/src/gen/optimize_code_size-long_type_bigint/google/protobuf/duration.ts
- packages/test-conformance/src/gen/optimize_code_size-long_type_bigint/google/protobuf/struct.ts
- packages/test-conformance/src/gen/optimize_code_size-long_type_bigint/google/protobuf/test_messages_proto2.ts
- packages/test-conformance/src/gen/optimize_code_size-long_type_bigint/google/protobuf/test_messages_proto3.ts
- packages/test-conformance/src/gen/optimize_code_size-long_type_string/conformance/conformance.ts
- packages/test-conformance/src/gen/optimize_code_size-long_type_string/google/protobuf/duration.ts
- packages/test-conformance/src/gen/optimize_code_size-long_type_string/google/protobuf/struct.ts
- packages/test-conformance/src/gen/optimize_code_size-long_type_string/google/protobuf/test_messages_proto2.ts
- packages/test-conformance/src/gen/optimize_code_size-long_type_string/google/protobuf/test_messages_proto3.ts
- packages/test-conformance/src/gen/optimize_speed-long_type_bigint/conformance/conformance.ts
- packages/test-conformance/src/gen/optimize_speed-long_type_bigint/google/protobuf/duration.ts
- packages/test-conformance/src/gen/optimize_speed-long_type_bigint/google/protobuf/struct.ts
- packages/test-conformance/src/gen/optimize_speed-long_type_bigint/google/protobuf/test_messages_proto2.ts
- packages/test-conformance/src/gen/optimize_speed-long_type_bigint/google/protobuf/test_messages_proto3.ts
- packages/test-conformance/src/gen/optimize_speed-long_type_string/conformance/conformance.ts
- packages/test-conformance/src/gen/optimize_speed-long_type_string/google/protobuf/duration.ts
- packages/test-conformance/src/gen/optimize_speed-long_type_string/google/protobuf/struct.ts
- packages/test-conformance/src/gen/optimize_speed-long_type_string/google/protobuf/test_messages_proto2.ts
- packages/test-conformance/src/gen/optimize_speed-long_type_string/google/protobuf/test_messages_proto3.ts
This change fixes all remaining conformance tests except for `Recommended.Proto2.JsonInput.FieldNameExtension.Validator` (and obviously all the text format ones). This brings protobuf-ts up to the same level of conformance as protobuf-es.
The reason that the `Required.Proto3.JsonInput.EnumFieldWithAliasLowerCase` and `Required.Proto3.JsonInput.EnumFieldWithAliasUseAlias` conformance tests were failing was because the [test_messages_proto3.proto](https://github.com/timostamm/protobuf-ts/compare/main...jcready:protobuf-ts:make-conformant?expand=1#diff-b256b7523b5b8cd27cc00490a71ce1e743ed2b83ff8f40b412966ffc7b2df98a) file hadn't been updated to match the [version of the conformance runner](https://github.com/timostamm/protobuf-ts/blob/2f0ed591475e943df16653d49f1ca9f1ec678fe7/packages/test-con …
> Make protobuf-ts as conformant as protobuf-es

- packages/plugin/src/message-type-extensions/well-known-types.ts
- packages/test-generated/spec/google.protobuf.field_mask.spec.ts
Fixes https://github.com/timostamm/protobuf-ts/issues/396
> Make FieldMask JSON read/write (snake_case <-> camelCase) conforming

- packages/runtime/spec/pb-long.spec.ts
- packages/runtime/src/goog-varint.ts
- packages/runtime/src/pb-long.ts
Initially my goal was simply to improve code coverage, but in doing so I discovered a number of issues related to pb-long when the test environment did not have BigInt support.
Issues discovered and fixed with pb-long w/o BI support:
1. `PbLong.from()` did not throw when the string value was too small `"-9223372036854775809"`, `"-18446744073709551616"`
2. https://github.com/timostamm/protobuf-ts/blob/2f0ed591475e943df16653d49f1ca9f1ec678fe7/packages/runtime/spec/pb-long.spec.ts#L133-L134 `Expected function to throw an Error.`
3. https://github.com/timostamm/protobuf-ts/blob/2f0ed591475e943df16653d49f1ca9f1ec678fe7/packages/runtime/spec/pb-long.spec.ts#L37-L40 `Expected '-1' to be '18446744073709551615'.`
4. https://github.com/timostamm/protobuf-ts/blob/2f0ed591475e943df16653d49f1ca9f1ec678 …
> Test pb-long without BI support and fix found issues

- packages/plugin/src/message-type-extensions/internal-binary-write.ts
fixes #610 
The generated code references the global `Object` (e.g. `Object.keys`) without explicitly referencing 'globalThis.' Therefore, if there is a message named 'Object,' issue arises due to incorrect reference (see details at #610). I modified it to access `Object` through `globalThis`.
> ref Object from globalThis in speed-optimized code for serializing map fields

- packages/plugin/src/message-type-extensions/create.ts
- packages/runtime/src/message-type-contract.ts
- packages/runtime/src/message-type.ts
- packages/runtime/src/reflection-create.ts
As mentioned in https://github.com/timostamm/protobuf-ts/issues/306#issuecomment-1711935782 there is a non-trivial performance hit for using `Object.defineProperty()`. Searching around you can find [plenty](https://github.com/mrdoob/three.js/issues/21284) of other [mentions](https://humanwhocodes.com/blog/2015/11/performance-implication-object-defineproperty/) of this.
Originally my plan was to create a `MessageInstance` class property on the base `MessageType` class and then call `const message = new this.MessageInstance()` inside the `create()` method. Unfortunately jasmine seems consider two object to **NOT** be deeply equal to each other when one was created via `new this.MessageInstance()` vs. an object literal with the exact same structure. However, if instead we utilize …
> Improve from Binary/Json/Partial performance by roughly 30%

- .github/workflows/ci.yaml
CI started failing with:
```
@protobuf-ts/twirp-transport: go: downloading google.golang.org/protobuf v1.33.0
Error: @protobuf-ts/twirp-transport: /home/runner/go/pkg/mod/github.com/golang/protobuf@v1.5.4/jsonpb/decode.go:19:2: //go:build comment without // +build comment
```
This updates to 1.17 to support the new build constraints.
> Update go version for twirp compat tests

- packages/runtime/src/message-type.ts
After https://github.com/timostamm/protobuf-ts/pull/582, message instances don't behave exactly like simple objects, as their prototype only includes a `Symbol("protobuf-ts/message-type")` field and is missing fields normally present in a simple object (e.g. `constructor`). For us, this specifically causes an issue when using [mobx](https://github.com/mobxjs/mobx)  to observe changes to message instances - it only allows observing objects that have a `constructor` method in their prototype that matches the method for simple objects.
This fixes the problem by copying the default object prototype and adding a `Symbol("protobuf-ts/message-type")` field, rather than starting from an empty prototype.
> Extend Object prototype for message instances

- packages/protoc/protoc.js
Now users can customize the protoc release url so that they can be downloaded from the mirror
> feat: add customize protoc release url

- packages/plugin/src/message-type-extensions/internal-binary-read.ts
> Read unknown fields even on empty messages

- packages/plugin/src/interpreter.ts
- packages/test-generated/spec/generated-binary-compat.spec.ts
Fixes https://github.com/timostamm/protobuf-ts/issues/453
Binary serialization is explicitly **not** expected to be consistent between different code generators and languages, but we should at least be self-consistent within protobuf-ts.
https://github.com/timostamm/protobuf-ts/blob/3a7ce47d43113d1a80cacd0ae70630b3727eda3e/packages/proto/google/protobuf/unittest.proto#L568-L570
> Make field writing order consistent between CODE_SIZE and SPEED

- packages/runtime-rpc/spec/server-streaming-call.spec.ts
- packages/runtime-rpc/src/rpc-output-stream.ts
> fix: always initialize iterator state in RpcOutputStreamController

- package.json
- packages/plugin-framework/turbo.json
- packages/plugin/spec/create-option-parser.spec.ts
- packages/plugin/src/framework/create-option-parser.ts
- packages/plugin/src/framework/plugin-base.ts
- packages/plugin/src/our-options.ts
- packages/plugin/src/protobufts-plugin.ts
This moves the logic for parsing plugin options received through CodeGeneratorRequest.parameter from plugin-base.ts to a separate file.
The new function createOptionParser returns a function that parses options from either a parameter string, or "raw options", a type that is compatible with parseOptions in @bufbuild/protoplugin (`{key: string, value: string}[]`).
> Split out plugin option parser

- packages/plugin/src/file-table.ts
- packages/plugin/src/interpreter.ts
- packages/plugin/src/options.ts
- packages/plugin/src/our-options.ts
- packages/plugin/src/out-file.ts
- packages/plugin/src/protobufts-plugin.ts
We define a few custom options in protobuf-ts.proto that affect code generation.
They are read from descriptors given to the plugin in interpreter.ts. Two interfaces and two enums are defined to match the types in protobuf-ts.proto.
This removes the 4 definitions with types generated from protobuf-ts.proto,
This also removes the OptionResolver class, moving the methods into InternalOptions.
> Simplify internal handling of protobuf-ts.proto options

- CONTRIBUTING.md
- README.md
- packages/README.md
- packages/plugin-framework/README.md
> [!IMPORTANT]
> 
> This plugin framework is deprecated.  
> For a good alternative, see [@bufbuild/protoplugin](https://www.npmjs.com/package/@bufbuild/protoplugin)
(The package isn't deprecated on npmjs.com yet, and is not removed from this repo or the release process yet.)
> Deprecate @protobuf-ts/plugin-framework

- packages/runtime/src/message-type.ts
Fixes https://github.com/timostamm/protobuf-ts/issues/724
There shouldn’t be any issue in mutating the `baseDescriptors` object directly since:
1. `Object.getOwnPropertyDescriptors()` always returns a referentially unique object every time it’s called.
2. `Object.create()` doesn’t retain any references to the second argument (the descriptors) in the resulting object.
```js
var a = Object.getPrototypeOf({});
var b = Object.getPrototypeOf({});
a === b; // true
var descriptor  = Object.getOwnPropertyDescriptors(a);
var descriptor2 = Object.getOwnPropertyDescriptors(a);
descriptor === descriptor2; // false
descriptor.field = {};
descriptor.field.value = 1;
var one = Object.create(null, descriptor);
one.field === 1; // true
descriptor.field.value = 2;
var two = Object.create(null, descriptor); …
```
> Work around global `Object.prototype` pollution

- packages/runtime/spec/message-type.spec.ts
- packages/runtime/src/message-type.ts
- packages/test-default/spec/message-type.spec.ts
- packages/test-force_optimize_code_size/spec/message-type.spec.ts
- packages/test-force_optimize_speed-long_type_string/spec/message-type.spec.ts
- packages/test-force_optimize_speed/spec/message-type.spec.ts
- packages/test-long_type_string/spec/message-type.spec.ts
Similar to https://github.com/timostamm/protobuf-ts/pull/728, this adds support for the MESSAGE_TYPE symbol property, added by `create()` since v2.0.3. See https://github.com/timostamm/protobuf-ts/pull/147 for context.
With this PR, `MessageType.equals` respects the MESSAGE_TYPE property: If either of both provided messages do not match the expected type, it returns false. Note that the added strictness can be considered a breaking change, same as with https://github.com/timostamm/protobuf-ts/pull/728.
> Support MESSAGE_TYPE in MessageType.equals

- packages/runtime/spec/message-type.spec.ts
- packages/runtime/src/message-type.ts
- packages/test-default/spec/message-type.spec.ts
- packages/test-force_optimize_code_size/spec/message-type.spec.ts
- packages/test-force_optimize_speed-long_type_string/spec/message-type.spec.ts
- packages/test-force_optimize_speed/spec/message-type.spec.ts
- packages/test-long_type_string/spec/message-type.spec.ts
Since v2.0.3, `create()` adds the MESSAGE_TYPE symbol property. See https://github.com/timostamm/protobuf-ts/pull/147 for context.
With this PR, `MessageType.is` and `MessageType.isAssignable` respect the MESSAGE_TYPE property:
- `ExampleMsg.is` will return whether the given value's `MESSAGE_TYPE.typeName` matches `ExampleMsg.typeName`. If MESSAGE_TYPE is not defined, `is` checks for matching properties recursively.
- `ExampleMsg.isAssignable` will return true if the given value's `MESSAGE_TYPE.typeName` matches `ExampleMsg.typeName`. Otherwise (also if MESSAGE_TYPE is not defined), it checks for matching properties recursively, ignoring excess properties.
This makes both methods more accurate, and allows `Timestamp.is` to distinguish a `Timestamp` from a `Duration`. 
With the added …
> Support MESSAGE_TYPE in MessageType.is and isAssignable
